name = "ai"
main = "worker.js"
compatibility_date = "2026-07-15"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = "."

# 内置AI绑定，无需API Token
[ai]
binding = "AI"