name = "ai"
# 必须存在这一行，指定worker入口
main = "worker.js"
compatibility_date = "2026-07-15"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = "."

# AI内置绑定，不需要token
[ai]
binding = "AI"